name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '*/5 * * * *'   # 每5分钟执行一次（可选）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'

    # 步骤1：运行根目录的 trace.go
    - name: Run trace
      run: go run trace.go

    # 步骤2：进入 openai 目录并运行 main
    - name: Run openai app
      working-directory: ./openai   # 指定工作目录为 openai
      run: go run .
